title: Alston Lo
name: Alston Lo
email: alston@mit.edu
description: The personal website of Alston Lo.
  
url: ""  # auto-set in deploy.yml
baseurl: "" 
icon: 🪴

lang: en

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

github_username:  alstonlo
linkedin_username: alston-lo
orcid_id: 0000-0003-1744-1446
scholar_userid: VPvuTtMAAAAJ

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

include: ['_pages']

# Plug-ins
plugins:
  - jekyll-postcss
  - jekyll-last-modified-at
  - jekyll-minifier

postcss:
  cache: false

jekyll-minifier:
  uglifier_args:
      harmony: true
