title: Alston Lo
author:
  name: Alston Lo
  email: alston@mit.edu
description: The personal website of Alston Lo.
  
url: ""  # auto-set in deploy.yml
baseurl: "" 
icon: 🪴
logo: /assets/img/aloe.png

lang: en

google_site_verification: bmt7ZR-4pF9c5fHwJtldiYJ_DcQYyfoykpQn8Op9DiE

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

github_username:  alstonlo
linkedin_username: alston-lo
orcid_id: 0000-0003-1744-1446
scholar_userid: VPvuTtMAAAAJ

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

include: ['_pages']

# Plug-ins
plugins:
  - jekyll-postcss
  - jekyll-last-modified-at
  - jekyll-minifier
  - jekyll-seo-tag
  - jekyll-sitemap

postcss:
  cache: false

jekyll-minifier:
  uglifier_args:
      harmony: true
